### ISSUE TITLE
Current build is broken due to ieee802154 changes

### ISSUE THREAD

**Issue by jamesmunns** [braun-robotics/rust-dwm1001#66]
It is currently (2019-01-29) not possible to build this crate, because at least the error types have changed.

CC @hannobraun

**Comment by hannobraun** [comment]
Thanks for the heads-up. Those are just some cosmetic changes in preparation of the upcoming first release of `ieee802154` on crates.io, so the fix is going to be easy. I'll try to get it done soon, hopefully tomorrow.

**Comment by jamesmunns** [comment]
I noticed because I'm giving a workshop with this today ;) for now I've pinned the Sha in a fork.

**Comment by hannobraun** [comment]
Sorry for the trouble! The (long overdue) crates.io releases will take care of this problem in the future, fortunately.

**Comment by hannobraun** [comment]
Fixed by https://github.com/braun-robotics/rust-dw1000/pull/65.
